name: Potfolio-angular

services:

  portfolio-angular:
      container_name: portfolio-angular
      build: .
      ports:
        - "4200:4200"
      environment:
        VIRTUAL_HOST: www.arthur-declerck.be
        VIRTUAL_PORT: 4200
        LETSENCRYPT_HOST: www.arthur-declerck.be
      networks:
      - portfolio-network

networks:
  portfolio-network:
    external: true